<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit16c9cd805281a0314b3abbb071ad233d
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OGalerie\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OGalerie\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit16c9cd805281a0314b3abbb071ad233d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit16c9cd805281a0314b3abbb071ad233d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit16c9cd805281a0314b3abbb071ad233d::$classMap;

        }, null, ClassLoader::class);
    }
}
